# Generated by Django 4.0.2 on 2025-10-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0014_alter_booking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
